name: Build & Push Docker Image to GHCR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment target (test or prod)"
        required: true
        default: "test"

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER_LC/philipjurke-${{ github.event.inputs.environment }}
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t $IMAGE_NAME:latest \
            --push .