name: Build and Deploy philipjurke

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set lower case repository name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ vars.PRODUCTION_URL }}

    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4
        with:
          repository: pjurke/infrastructure
          path: 'infrastructure'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Deploy to Staging
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: infrastructure/inventory.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --extra-vars "app_name=philipjurke env=staging image_tag=${{ github.sha }}"
            --tags staging,philipjurke

      - name: Deploy to Production
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: infrastructure/inventory.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --extra-vars "app_name=philipjurke env=production image_tag=${{ github.sha }}"
            --tags production,philipjurke
