name: Deploy PhilipJurke to Production (Build on Server)

on:
  push:
    branches:
      - main

jobs:
  deploy-philip-jurke-to-prod:

    name: Deploy PhilipJurke to Production Server via SSH
    runs-on: ubuntu-latest
    
    steps:
      
      # Step 1: Check out code from the repository
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      # Step 2: Log in to the VPS and run the deployment script
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /srv/web-apps/philipjurke/prod
            git pull origin main
            docker compose -f ../docker-compose.yml up --build -d
            docker image prune -f