name: Build & Push Docker Image to GHCR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment target (test or prod)"
        required: true
        default: "test"

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # --cache-from type=gha -> Tries to load the cache from GitHub Actions cache (GHAC)
      # --cache-to type=gha,mode=max -> Puts build layer to GHAC

      - name: Build and Push Docker Image
        run: |
          OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME=ghcr.io/$OWNER_LC/philipjurke-${{ github.event.inputs.environment }}
          
          CACHE_IMAGE_NAME=$IMAGE_NAME:buildcache

          echo "Building image: $IMAGE_NAME"
          echo "Using cache image: $CACHE_IMAGE_NAME"

          docker buildx create --use

          docker buildx build \
            --platform linux/arm64 \
            --cache-from type=registry,ref=$CACHE_IMAGE_NAME \
            --cache-to type=registry,ref=$CACHE_IMAGE_NAME,mode=max \
            -t $IMAGE_NAME:latest \
            --push .