name: Build and Deploy philipjurke

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Der Image-Tag ist der eindeutige Commit-SHA, z.B. ghcr.io/pjurke/textreview:a1b2c3d
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ vars.PRODUCTION_URL }}

    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4
        with:
          repository: pjurke/infrastructure # Dein Infra-Repo
          path: 'infrastructure'
          # Dieses Secret brauchst du, um auf dein privates Infra-Repo zugreifen zu können
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Deploy to Staging
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: infrastructure/inventory.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --extra-vars "app_name=philipjurke env=staging image_tag=${{ github.sha }}"
            --tags staging,philipjurke

      - name: Deploy to Production
        # Dieser Job läuft erst nach manueller Freigabe in der GitHub-UI
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: infrastructure/inventory.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --extra-vars "app_name=philipjurke env=production image_tag=${{ github.sha }}"
            --tags production,philipjurke
