name: Build and Deploy philipjurke

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set lower case repository name
        run: echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        run: |
          mkdir -p /run/containers/0
          podman login ghcr.io \
            -u "${{ github.actor }}" \
            -p "${{ secrets.GITHUB_TOKEN }}" \
            --authfile /run/containers/0/auth.json
          echo "REGISTRY_AUTH_FILE=/run/containers/0/auth.json" >> $GITHUB_ENV

      - name: Build Podman image with cache
        run: |
          podman build \
            --platform linux/arm64 \
            --layers \
            -t ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -f ./Dockerfile .

      - name: Tag image as 'latest'
        run: podman tag ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} ghcr.io/${{ env.IMAGE_NAME }}:latest

      - name: Push image to GHCR
        run: |
          podman push ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            --authfile /run/containers/0/auth.json
          podman push ghcr.io/${{ env.IMAGE_NAME }}:latest \
            --authfile /run/containers/0/auth.json

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ vars.PRODUCTION_URL }}

    steps:

      - name: Checkout Infrastructure Repository
        uses: actions/checkout@v4
        with:
          repository: pjurke/infrastructure
          path: 'infrastructure'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}

      - name: Deploy to Staging
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --inventory infrastructure/inventory.ini
            --extra-vars "app_name=philipjurke env=staging image_tag=${{ github.sha }}"

      - name: Deploy to Production
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: infrastructure/deploy-app.yml
          directory: ./
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          inventory: infrastructure/inventory.ini
          vault_password: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          options: |
            --inventory infrastructure/inventory.ini
            --extra-vars "app_name=philipjurke env=production image_tag=${{ github.sha }}"
