name: Build & Push Docker Image to GHCR

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment target (test or prod)"
        required: true
        default: "test"

jobs:
  build-and-push:
    name: Build and Push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry (GHCR)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set environment variables
        id: vars
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/philipjurke-${{ github.event.inputs.environment }}
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ steps.vars.outputs.image_name }}:latest .
          docker push ${{ steps.vars.outputs.image_name }}:latest