name: Build and publish Docker image for PhilipJurke

on:
  push:
    branches:
      - main

jobs:
  
  build-and-push-image:

    name: Build Docker image and publish it on ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      
      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Extract version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
      
      - name: Sign in for GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and publish Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
        