name: Deploy PhilipJurke to Production (Build on Server)

on:
  push:
    branches:
      - main

jobs:
  deploy-philip-jurke-to-prod:

    name: Deploy PhilipJurke to Production Server via SSH
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository code
        uses: actions/checkout@v4
      
      - name: Copy source code to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: "/srv/web-apps/philipjurke/prod"

      - name: Execute deployment script on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            echo "Executing deployment script on server..."
            /srv/web-apps/philipjurke/deploy.sh
            echo "Execution of the deployment script completed."