name: Deploy PhilipJurke to Production (Build on Server)

on:
  push:
    branches:
      - main

jobs:
  deploy-philip-jurke-to-prod:

    name: Deploy PhilipJurke to Production Server via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Production Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            echo "Executing deployment script on server..."
            DEPLOY_SCRIPT_PATH="/srv/web-apps/philipjurke/deploy.sh"
            ${DEPLOY_SCRIPT_PATH}
            echo "Execution of the deployment script completed."